### PR TITLE
Fix builds

### LINKED ISSUE #25: Dockerhub push failing in Travis
But the build itself passes.  :(

```
$ docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker build -t kontena/kosh:latest .; docker tag kontena/kosh:latest kontena/kosh:latest; docker push kontena/kosh:latest;
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #25 (automated builds to Docker Hub). Travis now also builds tags for each known cli version.

### CODE REVIEW

File: build/edge.sh [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#!/bin/bash
+
+if [ ! -z "$DOCKER_USERNAME" ] && [ ! -z "$DOCKER_PASSWORD" ]; then
+    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
+
+    docker build -t kontena/kosh:edge .
+    docker build --build-arg CLI_VERSION=1.2.0 -t kontena/kosh:edge-cli-1.2 .
+    docker build --build-arg CLI_VERSION=1.3.0 -t kontena/kosh:edge-cli-1.3 .
```
Comment (daniel-bytes) [inline build/edge.sh]: I suppose every time we release a point release we just add it here?

Comment (jakolehm) [inline build/edge.sh]: Yeah, we can always improve this.
